### ISSUE TITLE
print 'Sending %d bytes' % len(bytes) invalid syntax

### ISSUE THREAD

**Issue by 2n2n** [jdavisp3/twisted-intro#2]
I tried running your application **blocking-server/slowpoetry.py** with python 3.4 but when I execute: 

`python blocking-server/slowpoetry.py poetry/ecstasy.txt`

it says _invalid syntax on line 62_ but when I checked I think it's correct. maybe python version difference? It would really help if you would also create similar program for python3 as well?

**Comment by jdavisp3** [comment]
It must be yes, I never tried running this under Python 3.

**Comment by tripleee** [comment]
The Python 3 equivalent would be `print('Sending {0:d} bytes'.format(len(bytes)))` but porting to Python 3 is probably going to require a lot more than that.
