### ISSUE TITLE
Many problems with python 3.6

### ISSUE THREAD

**Issue by Patlol** [jdavisp3/twisted-intro#5]
Besides the print syntax becoming print() there are anyway some problems on python3.6 (or python3.x I guess) for example you need to use` .decode()` and `.encode()` to pass bytes to a string and vice versa
In blocking-client.py
`poem += data`
becomes
`poem += data.decode()`
In blocking-client.py again
`print'Got %d poems in %s' % (len(addresses), elapsed)`
object of type 'map' has no len(),  maybe it had one in 2.7? I don't know...
i use 
`print('Got %d poems in %s' % (i+1, elapsed))`

**But more serious** 
in `get_poetry(sockets)` from async.client.py
`sock2task = dict([(s, i + 1) for i, s in enumerate(sockets)) # => {}`
`sockets after sockets = list(sockets) # => []`
And of course async-client.py doesn't run!  
`./async-client/get-poetry.py 43264 43265 43266`
return :
`Got some poems in 0:00:00.000298`
and all the clients return:
```
blocking-server/slowpoetry.py --port 43264 poetry/ecstasy.txt
Serving poetry/ecstasy.txt on port 43264.
Somebody at ('127.0.0.1', 33832) wants poetry!
Sending 10 bytes
Sending 10 bytes
```  
etc  

If I were stronger I would correct all that, but I admit that correcting a program using notions that I try to learn is not easy for me. 

Too bad, I thought I had finally found the explanations necessary to understand asynchronous programming and exactly in the field I was looking for: networks.
And it is difficult to work in 2.7, the asyncio library having been largely modified between 2.7 and 3.6

**Comment by jdavisp3** [comment]
True! I wrote this for Python 2 and adding Python 3 support would be a lot of work. Also, it would probably make more sense to focus on the new `asyncio` stuff at first rather than Twisted. But, alas, I simply don't have time these days. Hope you find what you are looking for.

**Comment by jdavisp3** [comment]
Thanks, I happen to think it was too 😄

**Comment by Patlol** [comment]
It's never too much!!!  :)

**Comment by kvaml** [comment]
Would you be interested in pulling python3 versions of the programs? I do not guarantee I'll do them all, but I have been changing the .py files to Python3 syntax as I've been going through your code examples. I see no reason to preserve Python2 compatibility.

**Comment by jdavisp3** [comment]
> Would you be interested in pulling python3 versions of the programs? I do not guarantee I'll do them all, but I have been changing the .py files to Python3 syntax as I've been going through your code examples. I see no reason to preserve Python2 compatibility.

For sure! Appreciate any contributions you'd like to make.

**Comment by kvaml** [comment]
https://github.com/kvaml/twisted-intro/commits/py3

I forked your repository and started a py3 branch.

So far converting the code as been pretty painless
	2to3-3,5 gets the easy syntax stuff
	the bytes / unicode has been fairly easy so far

So I have found the effort educational and appreciate the effort you put into this very nice
tutorial.

I mostly use mercurial, so my git skills are not great. If I should have done something
differently, jut let me know.

On Sat, 2020-06-06 at 08:57 -0700, Dave Peticolas wrote:
> > Would you be interested in pulling python3 versions of the programs? I do not guarantee
> > I'll do them all, but I have been changing the .py files to Python3 syntax as I've been
> > going through your code examples. I see no reason to preserve Python2 compatibility.
> 
> For sure! Appreciate any contributions you'd like to make.
> 
-- 
Lloyd Kvam
5 Foliage View
Lebanon, NH 03766
802-448-0836

**Comment by jdavisp3** [comment]
Excellent! If you are interested in learning more about `git` I highly recommend the free labs at lab.github.com.

**Comment by kvaml** [comment]
I have converted the first 10 lessons. They are in the py3 branch at
https://github.com/kvaml/twisted-intro/commits/py3
I will send a pull request when I finish.

The conversion to Python3 highlights the switch between bytes on the network and unicode when working with the poems. I tried to put the bytes.decode('utf8') at the transition between twisted code  and the application that wants poetry. You might want to review the tutorial where you use "strings" somewhat interchangeably between byte and unicode strings which are now distinct.

The tutorial is fun, engaging, and very well thought out.

**Comment by jdavisp3** [comment]
Nice, glad you are enjoying it!

**Comment by jdavisp3** [comment]
I think we can resolve this, would you agree @kvaml ?

**Comment by kvaml** [comment]
Yes, this is resolved.

Your tutorial is excellent and now you have the Python 3 code to support it.

**Comment by jdavisp3** [comment]
Thanks @kvaml !
